version: 1
groups:
  # Internal options, that are used/computed by CKAN in runtime
  - annotation: ~
    options:
      - key: __file__
        internal: true
      - key: here
        internal: true
      - key: computed_template_paths
        ignored: true
      - key: clear_logo_upload
        ignored: true
      - key: logo_upload
        ignored: true
      - key: ckan.host
        ignored: true
      - key: ckanext.stats.cache_enabled
        ignored: true
        type: bool
      - key: testing
        ignored: true
        type: bool

  # Flask configuration options
  - annotation: ~
    options:
      - key: APPLICATION_ROOT
        internal: true
      - key: BABEL_DEFAULT_LOCALE
        internal: true
      - key: BABEL_DEFAULT_TIMEZONE
        ignored: true
      - key: BABEL_DOMAIN
        ignored: true
      - key: BABEL_MULTIPLE_DOMAINS
        ignored: true
      - key: BABEL_TRANSLATION_DIRECTORIES
        ignored: true
      - key: CKAN_INI
        internal: true
      - key: DEBUG
        internal: true
      - key: ENV
        internal: true
      - key: EXPLAIN_TEMPLATE_LOADING
        internal: true
      - key: JSONIFY_MIMETYPE
        internal: true
      - key: JSONIFY_PRETTYPRINT_REGULAR
        internal: true
      - key: JSON_AS_ASCII
        internal: true
      - key: JSON_SORT_KEYS
        internal: true
      - key: MAX_CONTENT_LENGTH
        internal: true
      - key: MAX_COOKIE_SIZE
        internal: true
      - key: PERMANENT_SESSION_LIFETIME
        internal: true
      - key: PREFERRED_URL_SCHEME
        internal: true
      - key: PRESERVE_CONTEXT_ON_EXCEPTION
        internal: true
      - key: PROPAGATE_EXCEPTIONS
        internal: true
      - key: SECRET_KEY
        internal: true
      - key: SEND_FILE_MAX_AGE_DEFAULT
        internal: true
      - key: SERVER_NAME
        internal: true
      - key: SESSION_COOKIE_DOMAIN
        internal: true
      - key: SESSION_COOKIE_HTTPONLY
        internal: true
      - key: SESSION_COOKIE_NAME
        internal: true
      - key: SESSION_COOKIE_PATH
        internal: true
      - key: SESSION_COOKIE_SAMESITE
        internal: true
      - key: SESSION_COOKIE_SECURE
        internal: true
      - key: SESSION_REFRESH_EACH_REQUEST
        internal: true
      - key: TEMPLATES_AUTO_RELOAD
        internal: true
      - key: TESTING
        internal: true
      - key: TRAP_BAD_REQUEST_ERRORS
        internal: true
      - key: TRAP_HTTP_EXCEPTIONS
        internal: true
      - key: USE_X_SENDFILE
        internal: true
      - key: DEBUG_TB_HOSTS
        internal: true
      - key: DEBUG_TB_ENABLED
        internal: true
      - key: DEBUG_TB_INTERCEPT_REDIRECTS
        internal: true
      - key: DEBUG_TB_PANELS
        internal: true

  # Global modifiers
  - annotation: ~
    options:
      - key: use
        default: egg:ckan
      - key: debug
        type: bool
      - key: config.safe
        type: bool
      - key: config.strict
        type: bool
      - key: config.normalized
        type: bool

  - annotation: Development settings
    options:
      - key: ckan.devserver.host
        default: localhost
      - key: ckan.devserver.port
        type: int
        default: 5000
      - key: ckan.devserver.threaded
        type: bool
      - key: ckan.devserver.multiprocess
        type: int
        default: 1
      - key: ckan.devserver.watch_patterns
      - key: ckan.devserver.ssl_cert
      - key: ckan.devserver.ssl_key


  - annotation: Session settings
    options:
      - key: cache_dir
        default: /tmp/%(ckan.site_id)s/
      - key: beaker.session.key
        default: ckan
      - key: beaker.session.secret
        default_callable: secrets:token_urlsafe
        default_args:
          nbytes: 20
        description: >-
          This is the secret token that the beaker library uses to hash the
          cookie sent to the client. `ckan generate config` generates a unique
          value for this each time it generates a config file.

  - annotation: repoze.who settings
    options:
      - key: who.config_file
        default: "%(here)s/who.ini"
      - key: who.log_level
        default: warning
      - key: who.log_file
        default: "%(cache_dir)s/who_log.ini"
      - key: who.timeout
        validators: ignore_empty convert_int
        disabled: true
        description: >-
          Session timeout (user logged out after period of inactivity, in
          seconds). Inactive by default, so the session doesn't expire.
      - key: who.httponly
        type: bool
        default: true
        disabled: true
      - key: who.secure
        type: bool
        disabled: true
      - key: who.samesite
        default: Lax
        disabled: true

  - annotation: Database settings
    options:
      - key: sqlalchemy.url
        default: postgresql://ckan_default:pass@localhost/ckan_default
        validators: not_empty
      - key: sqlalchemy.pool_pre_ping
        type: bool
        default: true
        disabled: true

  - annotation: Site Settings
    options:
      - key: ckan.site_url
        validators: not_empty
      - key: ckan.root_path

  - annotation: Authorization Settings
    options:
      - key: ckan.auth.anon_create_dataset
        type: bool
      - key: ckan.auth.create_unowned_dataset
        default: true
        type: bool
      - key: ckan.auth.create_dataset_if_not_in_organization
        default: true
        type: bool
      - key: ckan.auth.user_create_groups
        type: bool
      - key: ckan.auth.user_create_organizations
        default: true
        type: bool
      - key: ckan.auth.user_delete_groups
        type: bool
        default: true
      - key: ckan.auth.user_delete_organizations
        type: bool
        default: true
      - key: ckan.auth.create_user_via_api
        type: bool
      - key: ckan.auth.create_user_via_web
        type: bool
        default: true
      - key: ckan.auth.roles_that_cascade_to_sub_groups
        default: admin
      - key: ckan.auth.public_user_details
        type: bool
        default: true
      - key: ckan.auth.public_activity_stream_detail
        type: bool
        default: true
      - key: ckan.auth.allow_dataset_collaborators
        type: bool
      - key: ckan.auth.allow_admin_collaborators
        type: bool
      - key: ckan.auth.allow_collaborators_to_change_owner_org
        type: bool
      - key: ckan.auth.create_default_api_keys
        type: bool

  - annotation: API Token Settings
    options:
      - key: apikey_header_name
        default: X-CKAN-API-Key
        disabled: true
      - key: api_token.nbytes
        type: int
        default: 32
      - key: api_token.jwt.encode.secret
        default: string:%(beaker.session.secret)s
      - key: api_token.jwt.decode.secret
        default: "string:%(beaker.session.secret)s"
      - key: api_token.jwt.algorithm
        default: "HS256"

  - annotation: Search Settings
    options:
      - key: ckan.site_id
        default: default
      - key: solr_url
        default: http://127.0.0.1:8983/solr
        validators: not_empty
        disabled: true
      - key: solr_timeout
        disabled: true
        type: int
        default: 60
      - key: ckan.search.automatic_indexing
        disabled: true
        type: bool
        default: true
      - key: ckan.search.solr_commit
        disabled: true
        type: bool
        default: true
      - key: ckan.search.show_all_types
        disabled: true
        default: false
      - key: ckan.search.default_include_private
        disabled: true
        type: bool
        default: true
      - key: ckan.search.default_package_sort
        disabled: true
        default:  score desc, metadata_modified desc
      - key: ckan.datasets_per_page
        disabled: true
        type: int
        default: 20
      - key: search.facets.limit
        disabled: true
        type: int
        default: 50
      - key: search.facets.default
        disabled: true
        type: int
        default: 10
      - key: ckan.extra_resource_fields
        disabled: true
      - key: ckan.search.rows_max
        disabled: true
        type: int
        default: 1000
      - key: ckan.group_and_organization_list_max
        disabled: true
        type: int
        default: 1000
      - key: ckan.group_and_organization_list_all_fields_max
        disabled: true
        type: int
        default: 25


  - annotation: Redis Settings
    options:
      - key: ckan.redis.url
        disabled: true
        default: redis://localhost:6379/0
        validators: not_empty
        description: URL to your Redis instance, including the database to be used.

  - annotation: CORS Settings
    options:
      - key: ckan.cors.origin_allow_all
        type: bool
        disabled: true
        description: >-
          If cors.origin_allow_all is true, all origins are allowed.  If false,
          the cors.origin_whitelist is used.
      - key: ckan.cors.origin_whitelist
        disabled: true
        description: cors.origin_whitelist is a space separated list of allowed domains.

  - annotation: Plugins Settings
    options:
      - key: ckan.plugins
        description: |-
          Note: Add ``datastore`` to enable the CKAN DataStore.
          Add ``datapusher`` to enable DataPusher.
          Add ``resource_proxy`` to enable resorce proxying and get around the same origin policy.
      - key: ckan.views.default_views
        default: image_view recline_view
        description: >-
          Define which views should be created by default (plugins must be
          loaded in ckan.plugins)

  - annotation: Customize which text formats the text_view plugin will show
    options:
      - key: ckan.preview.json_formats
        default: json
        disabled: true
      - key: ckan.preview.xml_formats
        default: xml rdf rdf+xml owl+xml atom rss
        disabled: true
      - key: ckan.preview.text_formats
        default: txt plain text/plain
        disabled: true
      - key: ckan.preview.image_formats
        default: png jpeg jpg gif
        disabled: true
        description: >-
          Customize which image formats the image_view plugin will show
      - key: ckan.recline.dataproxy_url
        default: '//jsonpdataproxy.appspot.com'
        disabled: true

  - annotation: DataTables Settings
    options:
      - key: ckan.datatables.page_length_choices
        default: '20 50 100 500 1000'
      - key: ckan.datatables.state_saving
        type: bool
        default: true
      - key: ckan.datatables.state_duration
        type: int
        default: 7200
      - key: ckan.datatables.data_dictionary_labels
        type: bool
        default: true
      - key: ckan.datatables.ellipsis_length
        type: int
        default: 100
      - key: ckan.datatables.date_format
        default: llll
      - key: ckan.datatables.default_view
        default: table

  - annotation: Front-End Settings
    options:
      - key: ckan.site_title
        default: CKAN
      - key: ckan.site_logo
        default: /base/images/ckan-logo.png
      - key: ckan.site_description
      - key: ckan.favicon
        default: /base/images/ckan.ico
      - key: ckan.gravatar_default
        default: identicon
      - key: ckan.preview.direct
        default: png jpg gif
      - key: ckan.preview.loadable
        default: html htm rdf+xml owl+xml xml n3 n-triples turtle plain atom csv tsv rss txt json
      - key: ckan.display_timezone
        default: server
      - key: ckan.debug_supress_header
        type: bool
      - key: ckan.base_public_folder
        default: public
        disabled: true
      - key: extra_public_paths
        disabled: true
      - key: ckan.base_templates_folder
        default: templates
        disabled: true
      - key: extra_template_paths
        disabled: true
      - key: ckan.template_head_end
        disabled: true
      - key: ckan.template_footer_end
        disabled: true
      - key: ckan.template_title_delimiter
        default: '-'
      - key: ckan.homepage_style
        default: 1
        disabled: true
      - key: ckan.site_about
        disabled: true
      - key: ckan.main_css
        default: /base/css/main.css
        disabled: true
      - key: ckan.site_custom_css
        disabled: true
      - key: ckan.site_intro_text
        disabled: true
      - key: ckan.legacy_templates
        ignored: true
        type: bool

  # Not sure where these options must be stored
  - annotation: ~
    options:
      - key: licenses_group_url
        disabled: true

      - key: ckan.legacy_route_mappings
        default: '{"home": "home.index", "about": "home.about"}'
        disabled: true
      - key: ckan.cache_enabled
        disabled: true
        type: bool
      - key: ckan.cache_expires
        disabled: true
        default: 0
        type: int
      - key: ckan.mimetype_guess
        disabled: true
        default: file_ext
      - key: ckan.static_max_age
        disabled: true
        default: 3600
        type: int
      - key: ckan.tracking_enabled
        disabled: true
        type: bool
      - key: ckan.valid_url_schemes
        disabled: true
        default: http https ftp

      - key: ckan.resource_formats
        default: ckan/config/resource_formats.json
        disabled: true

      - key: ckan.dataset.create_on_ui_requires_resources
        type: bool
        default: true
        disabled: true

      - key: package_hide_extras
        disabled: true
      - key: package_edit_return_url
        disabled: true
      - key: package_new_return_url
        disabled: true

      - key: ckan.featured_groups
        disabled: true
      - key: ckan.featured_orgs
        disabled: true
      - key: ckan.default_group_sort
        default: title
        disabled: true


      - key: ckan.dumps_url
        disabled: true
      - key: ckan.dumps_format
        disabled: true


  - annotation: reCaptcha settings
    options:
      - key: ckan.recaptcha.publickey
        disabled: true
      - key: ckan.recaptcha.privatekey
        disabled: true

  - annotation: Internationalisation Settings
    options:
      - key: ckan.locale_default
        default: en
      - key: ckan.locale_order
      - key: ckan.locales_offered
      - key: ckan.locales_filtered_out
      - key: ckan.i18n_directory
      - key: ckan.i18n.extra_directory
      - key: ckan.i18n.extra_gettext_domain
      - key: ckan.i18n.extra_locales
      - key: ckan.i18n.rtl_languages
        default: he ar fa_IR
      - key: ckan.i18n.rtl_css
        default: /base/css/rtl.css

  - annotation: Feeds Settings
    options:
      - key: ckan.feeds.author_name
      - key: ckan.feeds.author_link
      - key: ckan.feeds.authority_name
      - key: ckan.feeds.date

  - annotation: Storage Settings
    options:
      - key: ckan.storage_path
        disabled: true
      - key: ckan.max_resource_size
        type: int
        default: 10
        disabled: true
      - key: ckan.max_image_size
        type: int
        default: 2
        disabled: true

  - annotation: Webassets Settings
    options:
      - key: ckan.webassets.use_x_sendfile
        type: bool
        disabled: true
      - key: ckan.webassets.path
        default: '%(ckan.storage_path)/webassets'
        disabled: true

  - annotation: User Settings
    options:
      - key: ckan.user_list_limit
        type: int
        default: 20
      - key: ckan.user_reset_landing_page
        default: home.index


  - annotation: Activity Streams Settings
    options:
      - key: ckan.activity_streams_enabled
        type: bool
        default: true
        disabled: true
      - key: ckan.activity_list_limit
        type: int
        default: 31
        disabled: true
      - key: ckan.activity_list_limit_max
        type: int
        default: 100
        disabled: true

      - key: ckan.activity_streams_email_notifications
        type: bool
        default: false
        disabled: true
      - key: ckan.email_notifications_since
        default: infinite
        disabled: true
      - key: ckan.hide_activity_from_users
        default: "%(ckan.site_id)s"

  - annotation: Email settings
    options:
      - key: email_to
        disabled: true
      - key: error_email_from
        disabled: true

      - key: smtp.server
        disabled: true
      - key: smtp.starttls
        type: bool
        disabled: true
      - key: smtp.user
        disabled: true
      - key: smtp.password
        disabled: true
      - key: smtp.mail_from
        disabled: true
      - key: smtp.reply_to
        disabled: true

  - annotation: Background Job Settings
    options:
      - key: ckan.jobs.timeout
        type: int
        default: 180
