name: Close inactive issues
on:
  schedule:
    - cron: "1 1 1 * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 730
          days-before-issue-close: 30
          stale-issue-label: "Inactive?"
          stale-issue-message: "This issue is stale because it has been open for 2 years with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale."
          days-before-pr-stale: 730
          days-before-pr-close: 30
          stale-pr-message: "This PR is stale because it has been open for 2 years with no activity."
          close-pr-message: "This PR was closed because it has been inactive for 30 days since being marked as stale."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
